- name: Create user on managed VM
  user:
    name: "{{ item.name }}"
    shell: /bin/bash
    state: present
    password: "*"
  loop: "{{ vm_users }}"

- name: Create .ssh directory for each user
  file:
    path: "/home/{{ item.name }}/.ssh"
    state: directory
    owner: "{{ item.name }}"
    group: "{{ item.name }}"
    mode: "0700"
  loop: "{{ vm_users }}"

- name: Deploy bastion public key for each user
  lineinfile:
    path: "/home/{{ item.name }}/.ssh/authorized_keys"
    line: "{{ item.bastion_public_key }}"
    create: yes
    owner: "{{ item.name }}"
    group: "{{ item.name }}"
    mode: "0600"
  loop: "{{ vm_users }}"

- name: Unlock user accounts
  command: usermod -p '*' "{{ item.name }}"
  loop: "{{ vm_users }}"
  changed_when: false

- name: Create bastion-logs user on S2-MT
  user:
    name: bastion-logs
    shell: /bin/bash
    state: present
    password: "*"
  when: inventory_hostname == 's2_mt'

- name: Unlock bastion-logs account
  command: usermod -p '*' bastion-logs
  when: inventory_hostname == 's2_mt'
  changed_when: false

- name: Create .ssh directory for bastion-logs
  file:
    path: /home/bastion-logs/.ssh
    state: directory
    owner: bastion-logs
    group: bastion-logs
    mode: "0700"
  when: inventory_hostname == 's2_mt'

- name: Deploy bastion system key for bastion-logs user
  lineinfile:
    path: /home/bastion-logs/.ssh/authorized_keys
    line: 'command="rsync --server -az --append . /var/log/bastion/bastion-auth.log",no-pty,no-agent-forwarding,no-port-forwarding {{ bastion_system_public_key }}'
    create: yes
    owner: bastion-logs
    group: bastion-logs
    mode: "0600"
  when: inventory_hostname == 's2_mt'
