- name: Configure managed VMs
  hosts: site1_app, site1_db, site2_mt
  become: true
  vars:
    vm_users:
      - name: lucas
        bastion_public_key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAII9sR53p4rYSNo3G751IqEs/PEOUv+ets1Zl9HKs1hTE"
        sudo: true
      - name: paul
        bastion_public_key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIDlPBWC0r+xCfzzSbug/n+ozOP7z7TOmFTol+QvqAGu5"
        sudo: true
      - name: andrej
        bastion_public_key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIIkimIhx57e/M/Glw4HZ+p2kmpxVZssPGhcxPUOd1p3C"
        sudo: true
    bastion_system_public_key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOPYi81/d96pnEde1kJs8IvLe210eMDrKQ+l/quFXWVt"
  roles:
    - managed_vm
