---
- name: Deploy NetBox on S2-MT
  hosts: site2_mt
  become: true
  vars_files:
    - ../group_vars/all/vars.yaml
  vars:
    netbox_version: "4.2.9"
    netbox_db_name: netbox
    netbox_db_user: netbox
    netbox_allowed_hosts:
      - "192.168.20.1"
      - "ops.site2.internal"
      - "localhost"

  pre_tasks:
    - import_tasks: tasks/vault_login.yml

    - name: Fetch NetBox secrets from Vault
      delegate_to: localhost
      run_once: true
      set_fact:
        netbox_db_password: "{{ _vault_netbox_db.data.data.password }}"
        netbox_secret_key:  "{{ _vault_netbox_django.data.data.secret_key }}"
        netbox_superuser_password: "{{ _vault_netbox_super.data.data.password }}"
      vars:
        _vault_netbox_db:     "{{ lookup('community.hashi_vault.vault_kv2_get', 'netbox/db',        url=vault_addr, ca_cert=vault_ca_cert, token=vault_token) }}"
        _vault_netbox_django: "{{ lookup('community.hashi_vault.vault_kv2_get', 'netbox/django',    url=vault_addr, ca_cert=vault_ca_cert, token=vault_token) }}"
        _vault_netbox_super:  "{{ lookup('community.hashi_vault.vault_kv2_get', 'netbox/superuser', url=vault_addr, ca_cert=vault_ca_cert, token=vault_token) }}"

  roles:
    - netbox
