---
- name: Cleanup fictive interfaces before sync
  hosts: localhost
  connection: local
  gather_facts: false
  vars_files:
    - ../group_vars/all/vars.yaml
  vars:
    netbox_url: "http://192.168.20.1"

  pre_tasks:
    - import_tasks: tasks/vault_login.yml

    - name: Fetch NetBox API token from Vault
      set_fact:
        netbox_token: "{{ _kv.data.data.token }}"
      vars:
        _kv: "{{ lookup('community.hashi_vault.vault_kv2_get', 'netbox/api', url=vault_addr, ca_cert=vault_ca_cert, token=vault_token) }}"

  tasks:
    - name: Remove fictive eth0 interfaces on synced VMs
      netbox.netbox.netbox_device_interface:
        netbox_url: "{{ netbox_url }}"
        netbox_token: "{{ netbox_token }}"
        data:
          device: "{{ item }}"
          name: "eth0"
        state: absent
      loop:
        - "S1-APP"
        - "S1-DB"
        - "S2-JS"
        - "S2-MT"
