- name: Installer les dépendances
  ansible.builtin.apt:
    name:
      - acl # requis pour become_user postgres
      - python3-psycopg2 # requis pour les modules ansible postgresql
    state: present
    update_cache: true

- name: Ajouter le repo officiel PostgreSQL
  ansible.builtin.shell: |
    curl -fsSL https://www.postgresql.org/media/keys/ACCC4CF8.asc \
      | gpg --dearmor -o /etc/apt/trusted.gpg.d/postgresql.gpg
    echo "deb https://apt.postgresql.org/pub/repos/apt $(lsb_release -cs)-pgdg main" \
      > /etc/apt/sources.list.d/pgdg.list
  args:
    creates: /etc/apt/sources.list.d/pgdg.list # idempotent

- name: Installer PostgreSQL {{ postgresql_version }}
  ansible.builtin.apt:
    name: "postgresql-{{ postgresql_version }}"
    state: present
    update_cache: true
  notify: restart postgresql

- name: S'assurer que PostgreSQL est démarré et activé
  ansible.builtin.systemd:
    name: postgresql
    state: started
    enabled: true

- name: Créer la base de données
  community.postgresql.postgresql_db:
    name: "{{ postgresql_db_name }}"
    encoding: UTF8
    lc_collate: fr_FR.UTF-8
    lc_ctype: fr_FR.UTF-8
    template: template0
    state: present
  become_user: postgres

- name: Créer l'utilisateur applicatif
  community.postgresql.postgresql_user:
    name: "{{ postgresql_db_user }}"
    password: "{{ postgresql_db_password }}"
    state: present
  become_user: postgres

- name: Donner les droits sur la DB
  community.postgresql.postgresql_privs:
    db: "{{ postgresql_db_name }}"
    role: "{{ postgresql_db_user }}"
    privs: ALL
    type: database
    state: present
  become_user: postgres

- name: Configurer pg_hba.conf
  ansible.builtin.template:
    src: pg_hba.conf.j2
    dest: "/etc/postgresql/{{ postgresql_version }}/main/pg_hba.conf"
    owner: postgres
    group: postgres
    mode: "0640"
  notify: reload postgresql

- name: Écouter sur toutes les interfaces (si accès réseau)
  ansible.builtin.lineinfile:
    path: "/etc/postgresql/{{ postgresql_version }}/main/postgresql.conf"
    regexp: "^#?listen_addresses"
    line: "listen_addresses = '*'"
  notify: restart postgresql
